name: 모델 생성 요청
description: 새로운 모델링 작업이나 기존 모델 개선을 위한 요청 사항입니다.
title: "[MODEL CREATION] " # 미리 채워진 제목 태그
labels: ["model-creation"] # 미리 채워진 라벨
assignees: [] # 담당자 지정, 있을 경우
body:
  - type: markdown
    attributes:
      value: |
        ## 모델 생성 요청
        모델을 생성하거나 개선하기 위한 상세한 요청 사항을 작성해 주세요. 명확한 요구사항은 모델링 과정의 성공을 위해 중요합니다.

  - type: textarea
    id: model-purpose
    attributes:
      label: 모델 목적
      description: 이 모델이 어떤 문제를 해결하거나 어떤 목적을 달성하는지 설명해주세요.
      placeholder: 모델의 목적을 상세하게 적어주세요.
    validations:
      required: true

  - type: textarea
    id: data-sources
    attributes:
      label: 데이터 출처
      description: 모델 학습에 사용될 데이터 버전을 적어주세요.
      placeholder: 데이터 버전, 추가한 피쳐등을 포함하여 적어주세요.
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: 예상 결과
      description: 모델링이 완료된 후 기대하는 결과나 출력을 설명해주세요.
      placeholder: 예상되는 모델의 출력과 성능 기준을 적어주세요.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: 제약 사항
      description: 모델 설계 및 개발 시 고려해야 할 제약 사항이 있다면 적어주세요.
      placeholder: 하드웨어 제한, 실행 시간 제한, 라이브러리 종속성 등 제약 사항을 적어주세요.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 이 모델 생성 요청과 관련하여 다른 팀원이 알아야 할 정보가 있으면 제공해주세요.
      placeholder: 기타 중요한 정보나 참고사항을 적어주세요.
    validations:
      required: false
